
package com.checkmarx.cxviewer.ws.resolver;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CxWSResolver", targetNamespace = "http://Checkmarx.com", wsdlLocation = "http://localhost:1515/Cxwebinterface/CxWsResolver.asmx?wsdl")
public class CxWSResolver
    extends Service
{

    private final static URL CXWSRESOLVER_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.checkmarx.cxviewer.ws.resolver.CxWSResolver.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.checkmarx.cxviewer.ws.resolver.CxWSResolver.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:1515/Cxwebinterface/CxWsResolver.asmx?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:1515/Cxwebinterface/CxWsResolver.asmx?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CXWSRESOLVER_WSDL_LOCATION = url;
    }

    public CxWSResolver(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CxWSResolver() {
        super(CXWSRESOLVER_WSDL_LOCATION, new QName("http://Checkmarx.com", "CxWSResolver"));
    }

    /**
     * 
     * @return
     *     returns CxWSResolverSoap
     */
    @WebEndpoint(name = "CxWSResolverSoap")
    public CxWSResolverSoap getCxWSResolverSoap() {
        return super.getPort(new QName("http://Checkmarx.com", "CxWSResolverSoap"), CxWSResolverSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CxWSResolverSoap
     */
    @WebEndpoint(name = "CxWSResolverSoap")
    public CxWSResolverSoap getCxWSResolverSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://Checkmarx.com", "CxWSResolverSoap"), CxWSResolverSoap.class, features);
    }

}
